# -*- coding: utf-8 -*-
"""create_lambda_function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sWC3i8G3S8o72rg4MQIrH565Mm0Cbbzs
"""

b = lambda x:x+25
print(b(10))