# -*- coding: utf-8 -*-
"""square the elements of a list using map().ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sWC3i8G3S8o72rg4MQIrH565Mm0Cbbzs
"""

Sample_List = [4, 5, 2, 9]
def sqr(x):
  x = x*x
  return x
lst = list(map(sqr,Sample_List))  
print(lst)