# -*- coding: utf-8 -*-
"""triple all numbers of a given list of integers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sWC3i8G3S8o72rg4MQIrH565Mm0Cbbzs
"""

sample_list = [1, 2, 3, 4, 5, 6, 7]
def num(x):
  x=x*3
  return x
lst = list(map(num,sample_list))
print(lst)